package com.luotr.model.entity;

public class user {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Wed May 09 16:12:10 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Wed May 09 16:12:10 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pwd
     *
     * @mbg.generated Wed May 09 16:12:10 CST 2018
     */
    private Integer pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sales_id
     *
     * @mbg.generated Wed May 09 16:12:10 CST 2018
     */
    private Integer salesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Wed May 09 16:12:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Wed May 09 16:12:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Wed May 09 16:12:10 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Wed May 09 16:12:10 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pwd
     *
     * @return the value of user.pwd
     *
     * @mbg.generated Wed May 09 16:12:10 CST 2018
     */
    public Integer getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pwd
     *
     * @param pwd the value for user.pwd
     *
     * @mbg.generated Wed May 09 16:12:10 CST 2018
     */
    public void setPwd(Integer pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sales_id
     *
     * @return the value of user.sales_id
     *
     * @mbg.generated Wed May 09 16:12:10 CST 2018
     */
    public Integer getSalesId() {
        return salesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sales_id
     *
     * @param salesId the value for user.sales_id
     *
     * @mbg.generated Wed May 09 16:12:10 CST 2018
     */
    public void setSalesId(Integer salesId) {
        this.salesId = salesId;
    }
}